name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.4', '8.0', '8.1', '8.2' ]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer"
      - name: Composer
        run: composer install

      - name: Tests
        run: ./vendor/bin/phpunit ./tests
